home = "chifi/ChifiDocs"
[chifi]
color = "white"
txtcolor = "#333333"
icon = "/ecosystems/chifi.png"
description = ""

[chifi.ChifiDocs]
path = "chifi/ChifiDocs"
color = "#FDB0C0"

[chifi.Documator]
path = "chifi/Documator"
color = "#6682E0"

[chifi.CarouselArrays]
path = "chifi/CarouselArrays"
color = "#B3438F"

[chifi.ChiProxy]
path = "chifi/ChiProxy"
color = "#40859c"

[parametric]
color = "#333333"
txtcolor = "white"
icon = "/ecosystems/parametric.png"

[parametric.ParametricProcesses]
path = "parametric/ParametricProcesses"
color = "#75B2C8"
txtcolor = "white"

[parametric.IPyCells]
path = "parametric/IPyCells"
color = "#c91a43"
txtcolor = "white"

[parametric.ParametricScheduler]
path = "parametric/ParametricScheduler"
color = "#FF7860"
txtcolor = "white"

[toolips]
color = "#75B2C8"
txtcolor = "white"
icon = "/ecosystems/toolips.png"
description = "The `Toolips` ecosystem provides an inclusive and modular web-development suite for the Julia language."

[toolips.ToolipsServables]
path = "toolips/ToolipsServables"
color = "#5C73D0"

[toolips.Toolips]
path = "toolips/Toolips"
color = "#6F7BA8"

[toolips.ToolipsSession]
path = "toolips/ToolipsSession"
color = "#FF4F4B"

[toolips.ToolipsSVG]
path = "toolips/ToolipsSVG"
color = "#723176"

[toolips.ToolipsUDP]
path = "toolips/ToolipsUDP"
color = "#D2B752"

[gattino]
color = "#C178B5"
txtcolor = "white"
icon = "/ecosystems/gattino.png"

[gattino.Gattino]
path = "gattino/Gattino"
color = "#2A0134"

[gattino.GattinoPleths]
path = "gattino/GattinoPleths"
color = "#FF7F7F"

[olive]
color = "#FFA7D3"
txtcolor = "white"
icon = "/ecosystems/olive.png"

[olive.Olive]
path = "olive/Olive"
color = "#FDB0C0"

[olive.OliveHighlighters]
path = "olive/OliveHighlighters"
color = "#7b32a8"

[olive.OlivePython]
path = "olive/OlivePython"
color = "#32a852"

[olive.OliveDocBrowser]
path = "olive/OliveDocBrowser"
color = "#AA336A"
txtcolor = "#1e1e1e"

[algebraframes]
color = "#ba9604"
icon = "/ecosystems/algebraframes.png"
txtcolor = "white"

[algebraframes.AlgebraFrames]
path = "algebraframes/AlgebraFrames"
color = "#891496"

[tumble]
color = "#D73636"
txtcolor = "white"
icon = "/ecosystems/tumble.png"

[tumble.Tumble]
path = "tumble/Tumble"
color = "#9c2525"
