[chifi]
color = "white"
txtcolor = "#333333"
icon = "/ecosystems/chifi.png"

[chifi.ChifiDocs]
path = "chifi/ChifiDocs"
color = "#FDB0C0"
pages = ["welcome", "welcome.md", "chifi", "chifi.md"]

[parametric]
color = "#333333"
txtcolor = "white"
icon = "/ecosystems/parametric.png"

[parametric.ParametricProcesses]
color = "#75B2C8"
txtcolor = "white"

[toolips]
color = "#75B2C8"
txtcolor = "white"
icon = "/ecosystems/toolips.png"

[toolips.Toolips]
path = "toolips/Toolips"
color = "#adc2c9"
pages = ["getting-started", "firstoverview.md", "responses", "the_response.md", "extensions", "extensions.md"]

[toolips.ToolipsSession]
path = "toolips/ToolipsSession"
color = "#FF4F4B"
pages = []

[gattino]
color = "#C178B5"
txtcolor = "#333333"
icon = "/ecosystems/gattino.png"

[gattino.Gattino]
path = "gattino/Gattino"
color = ""
pages = []


