[emmaccode]
name = "emmac"
ecosystems = ["chifi", "parametric", "toolips", "gattino", "olive"]
[Keno]
name = "Keno Fischer"
ecosystems = ["toolips"]
[fonsp]
name = "Fons van der Plas"
ecosystems = ["olive"]

[UnformalPenguin]
name = "Penguin"
ecosystems = ["toolips", "olive"]

[braamvandyk]
name = "Braam van Dyk"
ecosystems = []