[chifi]
color = "white"
txtcolor = "#333333"
icon = ""

[chifi.ChifiDocs]
path = "chifi/ChifiDocs"
color = ""
pages = ["welcome", "welcome.md"]

[parametric]
color = "#333333"
txtcolor = "white"
icon = ""

[parametric.ParametricProcesses]
color = "#75B2C8"
txtcolor = "white"

[toolips]
color = "#75B2C8"
txtcolor = "white"
icon = ""

[toolips.Toolips]
path = "toolips/Toolips"
color = ""
pages = ["getting-started", "firstoverview.md"]

[toolips.ToolipsSession]
path = "toolips/ToolipsSession"
color = ""
pages = ["nil"]

[gattino]
color = "#C178B5"
txtcolor = "white"
icon = ""

[gattino.Gattino]
path = "gattino/Gattino"
color = ""
pages = []


